name: educhat
description: "A Cross-Platform Communication Platform for Learners"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Core
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.0

  # Network & API
  supabase_flutter: ^2.0.2
  dio: ^5.4.0
  http: ^1.1.2

  # UI Components
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  url_launcher: ^6.2.2
  
  # Video Calls
  jitsi_meet_wrapper: ^0.2.0+1

  # Local Storage & Caching
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utils
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  intl: ^0.19.0
  logger: ^2.0.2+1
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
